[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    https://github.com/ricardoquesada/bluepad32-arduino.git
build_flags =
    -DCORE_DEBUG_LEVEL=0
    -DCONFIG_BLUEPAD32_MAX_DEVICES=1
