[env:esp32dev]
platform = espressif32@6.10.0
board = esp32dev
framework = arduino
monitor_speed = 115200
platform_packages =
    framework-arduinoespressif32 @ https://github.com/ricardoquesada/esp32-arduino-lib-builder/releases/download/4.1.0/esp32-bluepad32-4.1.0.zip
build_flags =
    -DCORE_DEBUG_LEVEL=0
    -DCONFIG_BLUEPAD32_MAX_DEVICES=1
